### ISSUE TITLE
failed: No such file or directory

### ISSUE THREAD

**Issue by Vaporwave-Skeleton** [EvilSupahFly/Amulet-Flatpak#3]
I am on a Linux Mint machine, and have very limited experience with terminal commands, so it is possible I have made a silly mistake.
I attempted to perform the command `flatpak install amulet.flatpak` as instructed in the guide and simply got the error `failed: No such file or directory`. I tried as well to do `flatpak update --appstream` in case this was the issue but still had no luck afterwards. Even attempts to do `flatpak search amulet.flatpak` or `flatpak search amulet` yields nothing, as if the flatpak doesnt exist at all. Its possible this is an error on my part, if so, I apologize.

**Comment by EvilSupahFly** [comment]
That's not your fault. I don't have Amulet registered on Flathub yet because I have some bugs to work out still. Currently, the only way to get the flatpak is to actually build it yourself, which is a currently not quite working properly. Once it's available, the flatpak will be available for download here.

**Comment by Vaporwave-Skeleton** [comment]
Thank you for responding. I will eagerly await a further update :)

**Comment by EvilSupahFly** [comment]
Until I can secure a hub, you'll have to download the flatpak manually from the [Releases](https://github.com/EvilSupahFly/Amulet-Flatpak/releases) tab.

To install it, open a terminal and go to the folder you saved it to (for example: `cd /home/evilsupahfly/Downloads/amulet-flatpak/`) and run the flatpak installer with `flatpak install amulet.flatpak`.

After that, you can run Amulet by typing `flatpak run com.github.amulet_map_editor`.

I should probably publish a script or `.desktop` launcher for it too...
